//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your own color.
        /// </summary>
        public static string Chooseyourowncolor {
            get {
                return ResourceManager.GetString("Chooseyourowncolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use this Email Address.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string Invalidemail {
            get {
                return ResourceManager.GetString("Invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname already taken.
        /// </summary>
        public static string NicknameExists {
            get {
                return ResourceManager.GetString("NicknameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname MUST be at least 6 chars and not longer than 12 chars .
        /// </summary>
        public static string NicknameLengh {
            get {
                return ResourceManager.GetString("NicknameLengh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string RegistrationAboutUs {
            get {
                return ResourceManager.GetString("RegistrationAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Your Color.
        /// </summary>
        public static string RegistrationChoseColor {
            get {
                return ResourceManager.GetString("RegistrationChoseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string RegistrationConfirmPassword {
            get {
                return ResourceManager.GetString("RegistrationConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string RegistrationCountry {
            get {
                return ResourceManager.GetString("RegistrationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create My Account.
        /// </summary>
        public static string RegistrationCreateMyAccount {
            get {
                return ResourceManager.GetString("RegistrationCreateMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string RegistrationEnterEmail {
            get {
                return ResourceManager.GetString("RegistrationEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string RegistrationEnterPassword {
            get {
                return ResourceManager.GetString("RegistrationEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string RegistrationForgotPassword {
            get {
                return ResourceManager.GetString("RegistrationForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string RegistrationGender {
            get {
                return ResourceManager.GetString("RegistrationGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts Language.
        /// </summary>
        public static string RegistrationLanguage {
            get {
                return ResourceManager.GetString("RegistrationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string RegistrationLogin {
            get {
                return ResourceManager.GetString("RegistrationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegistrationMail {
            get {
                return ResourceManager.GetString("RegistrationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        public static string RegistrationNickName {
            get {
                return ResourceManager.GetString("RegistrationNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nickname cannot be changed later).
        /// </summary>
        public static string RegistrationNickNameSup {
            get {
                return ResourceManager.GetString("RegistrationNickNameSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegistrationPassword {
            get {
                return ResourceManager.GetString("RegistrationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string RegistrationPrivacy {
            get {
                return ResourceManager.GetString("RegistrationPrivacy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        public static string RegistrationTermsOfUse {
            get {
                return ResourceManager.GetString("RegistrationTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Of Birth.
        /// </summary>
        public static string RegistrationYearOfBirth {
            get {
                return ResourceManager.GetString("RegistrationYearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Requiredfield {
            get {
                return ResourceManager.GetString("Requiredfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept our terms.
        /// </summary>
        public static string TermsAccept {
            get {
                return ResourceManager.GetString("TermsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This nickname already taken.
        /// </summary>
        public static string Thisnicknamealreadytaken {
            get {
                return ResourceManager.GetString("Thisnicknamealreadytaken", resourceCulture);
            }
        }
    }
}
