//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Resources.ru", typeof(Resources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Chooseyourowncolor {
            get {
                return ResourceManager.GetString("Chooseyourowncolor", resourceCulture);
            }
        }
        
        public static string CultureId {
            get {
                return ResourceManager.GetString("CultureId", resourceCulture);
            }
        }
        
        public static string FaceBookID {
            get {
                return ResourceManager.GetString("FaceBookID", resourceCulture);
            }
        }
        
        public static string GeneratedLink {
            get {
                return ResourceManager.GetString("GeneratedLink", resourceCulture);
            }
        }
        
        public static string IncorrectPhone {
            get {
                return ResourceManager.GetString("IncorrectPhone", resourceCulture);
            }
        }
        
        public static string Invalidemail {
            get {
                return ResourceManager.GetString("Invalidemail", resourceCulture);
            }
        }
        
        public static string TermsAccept {
            get {
                return ResourceManager.GetString("TermsAccept", resourceCulture);
            }
        }
        
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        public static string Requered {
            get {
                return ResourceManager.GetString("Requered", resourceCulture);
            }
        }
        
        public static string Requiredfield {
            get {
                return ResourceManager.GetString("Requiredfield", resourceCulture);
            }
        }
        
        public static string SpecialDates {
            get {
                return ResourceManager.GetString("SpecialDates", resourceCulture);
            }
        }
        
        public static string Thisnicknamealreadytaken {
            get {
                return ResourceManager.GetString("Thisnicknamealreadytaken", resourceCulture);
            }
        }
        
        public static string UEmail {
            get {
                return ResourceManager.GetString("UEmail", resourceCulture);
            }
        }
        
        public static string UName {
            get {
                return ResourceManager.GetString("UName", resourceCulture);
            }
        }
        
        public static string UPhone {
            get {
                return ResourceManager.GetString("UPhone", resourceCulture);
            }
        }
        
        public static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }
        
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
